<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Create User') ?></h2>
        <p><?php echo sprintf($this->translate('Creates a user for the doctrine2 Getting-Started bugtracker')) ?></p>
        <p><a class="btn btn-success" href="/user"><?php echo $this->translate('Create user') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Create Product') ?></h2>
        <p><?php echo sprintf($this->translate('Creates a product for the doctrine2 Getting-Started bugtracker')) ?></p>
        <p><a class="btn btn-success" href="/product"><?php echo $this->translate('Create product') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Create Bug') ?></h2>
        <p><?php echo sprintf($this->translate('Creates a bug for the doctrine2 Getting-Started bugtracker')) ?></p>
        <p><a class="btn btn-success" href="/application/bug/create"><?php echo $this->translate('Create bug') ?> &raquo;</a><a class="btn btn-success" href="/application/bug/list"><?php echo $this->translate('List bug') ?> &raquo;</a><a class="btn btn-success" href="/application/bug/close"><?php echo $this->translate('Close bug') ?> &raquo;</a><a class="btn btn-success" href="/application/bug/listrepository"><?php echo $this->translate('Bug repository') ?> &raquo;</a><a class="btn btn-success" href="/application/bug/dashboard"><?php echo $this->translate('Dashboard') ?> &raquo;</a></p>
   </div>
</div>