<a href="<?php echo $this->url('bug') ?>">&lt;&lt; Back to Bugtracker</a><br/>
<?php foreach($bugs as $bug):?>
	<?= $bug->getDescription(); ?> - <?=  $bug->getCreated()->format('d.m.Y')?><br/>
	Reported by: <?=  $bug->getReporter()->getName(); ?><br/>
	Assigned to: <?= $bug->getEngineer()->getName(); ?><br/>
	<?php foreach($bug->getProducts() as $product):?>
		Platform: <?= $product->getName(); ?>
	<?php endforeach;?>
	<hr/>
<?php endforeach;?>
