
<a href="<?php echo $this->url('bug') ?>">&lt;&lt; Back to Bugtracker</a><br/>
<?php foreach($bugs AS $bug): ?>
	<b><?= $bug->getDescription(); ?></b> (<?= $bug->getCreated()->format('d.m.Y'); ?>)
	Reported:  <?= $bug->getReporter()->getName() ?> - 
	Assigned:  <?= $bug->getEngineer()->getName() ?><br/>
	Platforms:<ul>
	<?php foreach($bug->getProducts() as $product):?>
		 <li><?= $product->getName() ?></li>
	<?php endforeach; ?>
	</ul>
<?php endforeach; ?>